Add alpha message
aerospike/aerospike-backup-service pull request #120
Opened 2024-01-24 22:42 UTC by hev

2024-01-24 23:56 UTC, arrowplum requested changes
Seems overkill to "request changes" but at least the spelling should be fixed.

2024-01-24 23:56 UTC, arrowplum commented on README.md
> +Aerospike Backup Service is currently in Alpha. Production usage is not reccomended and changes may occur.
```suggestion
Aerospike Backup Service is currently in pre-alpha. Production usage is not recommended and changes to the API are likely to occur.
```

2024-01-25 00:12 UTC, arrowplum commented on README.md
> +Aerospike Backup Service is currently pre Alpha. Production usage is not reccomended and changes may occur.
```suggestion
Aerospike Backup Service is currently pre Alpha. Production usage is not recommended and changes may occur.
```

2024-01-25 00:19 UTC, arrowplum approved these changes

2024-01-25 07:37 UTC, reugn commented on README.md
> +```
I suggest using the [Alerts Markdown](https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/) extension
```
> [!NOTE]  
> Aerospike Backup Service is currently pre Alpha. Production usage is not recommended and changes may occur.
> Enterprise customers, please contact support to sign an Alpha agreement. 
```
and putting the message under the status badges.

2024-01-30 08:33 UTC, reugn approved these changes

2024-01-30 08:34 UTC, merged